### PR TITLE
add maven resource filtering for marathon config file

### PR DESCRIPTION
**Pull request by gazal-k**
Add maven resource filtering so that marathon config file is easier to customise.

Just like https://github.com/marccarre/properties-files-maven-plugin/issues/7 maven filtering fails in tests. Verified manually.

### CODE REVIEW

**Comment by gazal-k** [comment]
On second thought, I wonder if the processConfig mojo can be replaced with maven resource filtering. Thoughts?

**Comment by mjakubowski84** [comment]
Hi, @gazal-k !
Thanks for your PR! Indeed testing mojos based on components is not an easy task :). In order to do that we need to use stubs in test plugin configuration. Currently tests in this project are instantiated using plugin's pom as a base for testing what maybe is not a best solution. 
But the idea of a solution is that for any mojo you can have a configuration with stubs, e.g. like that:

```
<project implementation="org.apache.maven.plugin.testing.stubs.MavenProjectStub"/>
<!-- use a test stub here, too!!! -->
<resourcesFiltering implementation="org.apache.maven.shared.filtering.DefaultMavenResourcesFiltering"/>
```

The same configuration may come from pom.xml but I believe it may be set programatically, too. Let me check it.

**Comment by gazal-k** [comment]
@mjakubowski84 thanks for the tip on testing filtering in this plugin. But I think this PR maybe unnecessary. I tried using `maven-resources-plugin` directly as a solution to the same problem this PR was meant to solve. My inference is that, `maven-resources-plugin` can be used instead of `processConfig` goal.

**Comment by mjakubowski84** [comment]
@gazal-k This plugin was created quite a long time ago... but I believe that we didn't want to have dependency to another plugin. Moreover, model parsing allows us to validate the schema while processing it.

And yes, you are right - maven resources plugin run before deploy will help you to achieve your goal. If it is ok for you please close the PR then.

**Pull request closed without merging**
