### PR TITLE
use official marathon-client dependency

### PR DESCRIPTION
**Pull request by gazal-k**
it is not available in maven central though, will have to wait for
https://github.com/mesosphere/marathon-client/issues/14

### CODE REVIEW

**Comment by gazal-k** [comment]
Added the mesosphere repository for the new client dependency, but facing the issue mentioned here: https://github.com/mesosphere/marathon-client/issues/14#issuecomment-233625890

**Comment by krystiannowak** [comment]
So, @gazal-k - since http://search.maven.org/#artifactdetails%7Ccom.mesosphere%7Cmarathon-client%7C0.2.1%7Cjar went public as per https://github.com/mesosphere/marathon-client/issues/14#issuecomment-234679744 - therefore https://github.com/gazal-k/marathon-maven-plugin/blob/marathon-client-update/pom.xml#L304 might be removed now

**Comment by gazal-k** [comment]
@krystiannowak done

**Comment by krystiannowak** [comment]
@gazal-k - thanks! I could build it successfully :)
@mjakubowski84 - LGTM for merge?

**Comment by mjakubowski84** [comment]
👍

**Pull request merged**
